language: c

sudo: true

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -y libmcrypt-dev gcc-5 g++-5
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      sudo mkdir /usr/local/build_env
      sudo mv cmake /usr/local/build_env
    fi
before_script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - (mkdir build && cd build && /usr/local/build_env/cmake/bin/cmake -DWITH_TESTS=ON ..)

script:
  - (cd build && make)
  - bash ./bin/run_tests.bash